### ISSUE TITLE
Embed form di inserimento ricette

### ISSUE THREAD

**Issue by aborruso** [Escilaricetta/recipe-site#1]
@piersoft o @iltempe che ne dite di inerirlo in una pagine in corrispondenza del menu "Inserisci la tua ricetta"?

Se siete d'accordo potete clonare una delle pagine esistenti, o mi incollate qui il codice di embedding

**Comment by piersoft** [comment]
<iframe src="
https://docs.google.com/forms/d/1YlCInvvavMrxSMrOe0A-pdXbiWs-nWHdc27lo4ixexY/viewform?embedded=true"
width="760" height="500" frameborder="0" marginheight="0"
marginwidth="0">Caricamento in corso...</iframe>

Il giorno 24 gennaio 2016 18:35, Andrea Borruso notifications@github.com
ha scritto:
