### ISSUE TITLE
Pagina con accesso ai dati e licenza

### ISSUE THREAD

**Issue by aborruso** [Escilaricetta/recipe-site#4]
C'è da preparare una pagina con l'accesso ai dati aperti, affiancati da una licenza di utilizzo.

**Comment by iltempe** [comment]
ok. Facciamo un link al CSV dei dati?

**Comment by aborruso** [comment]
On 24 January 2016 at 21:48, IlTempe notifications@github.com wrote:

> ok. Facciamo un link al CSV dei dati?

Yes.

In Petrusino abbiamo fatto una pagina "Open
http://petrusino.opendatasicilia.it/open.html" con il link di accesso ai
dati (html e csv con datapackage) e con un elenco di strumenti usati.
Si potrebbe ripetere una cosa simile.

## 

Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus  http://bit.ly/GEOplus

## 38° 7' 48" N, 13° 21' 9" E, EPSG:4326

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by iltempe** [comment]
ok. per ora ho messo un link sulla barra menu. procedo anche a fare una pagina Open dove mettiamo dati e strumenti usati.
